services:
  - type: web
    name: CafeCorner
    env: python
    buildCommand:
      - pip install -r requirements.txt
      - python manage.py collectstatic --noinput
    startCommand: gunicorn CafeCorner.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        value: "postgresql://cafecorner_user:fnfMb7YTLj6DSQEyhI1HXs8MhhDEji3w@dpg-cvdlh45rie7s73em2f80-a.frankfurt-postgres.render.com:5432/cafecorner"
      - key: SECRET_KEY
        value: "django-insecure-ggl)c#6+nvqpfqos#=cuitqwa67la$qc+yr-otxly%nj!+a-@)"
      - key: DEBUG
        value: False
      - key: CLOUDINARY_CLOUD_NAME
        value: "dfk7crlez"
      - key: CLOUDINARY_API_KEY
        value: "299735692388289"
      - key: CLOUDINARY_API_SECRET
        value: "feAGHPHnsu5yFWSOdjGkv1ir6tw"
