# Generated by Django 5.0.3 on 2025-03-18 18:51

import django.db.models.deletion
from django.db import migrations, models
class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CafeShop",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("introduction", models.TextField(blank=True, null=True)),
                ("address", models.CharField(max_length=255)),
                ("contact", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "price_range",
                    models.CharField(
                        choices=[
                            ("£0-10", "£0-10"),
                            ("£10-20", "£10-20"),
                            ("£20-30", "£20-30"),
                            ("£30-40", "£30-40"),
                            ("£40-50", "£40-50"),
                            ("over £50", "over £50"),
                        ],
                        default="£0-10",
                        max_length=10,
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                (
                    "img",
                    models.ImageField(blank=True, null=True, upload_to="cafe_images/"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.cafeowner",
                    ),
                ),
            ],
            options={
                "db_table": "cafe_shop",
            },
        ),
    ]
