# Generated by Django 5.0.3 on 2025-03-19 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cafeshop",
            name="img",
        ),
        migrations.AddField(
            model_name="cafeshop",
            name="img_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
